config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

    root 'products#index'
    resources :products, only: [:index, :new, :create]
    resources :shopping_carts, only: [:index, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_and_belongs_to_many :shopping_carts
  validates_presence_of :name, :item_type, :price
  scope :search, -> (search_term) { where('name ILIKE :query OR item_type ILIKE :query OR price ILIKE :query OR brand_name ILIKE :query', query: "%#{search_term}%") }
  validates :price, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many  :users
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base

  has_and_belongs_to_many :products
  belongs_to  :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to  :role
  has_one :shopping_cart

  after_create  :create_shopping_cart_for_user

  def create_shopping_cart_for_user
    ShoppingCart.create!(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = if params[:search_term].present?
      Product.search(params[:search_term])
    else
      Product.all
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = I18n.t('products.create')
      redirect_to products_path
    else
      flash[:error] = @product.errors.full_messages.first
      redirect_to new_product_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :item_type, :price, :brand_name, :serial_number)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    # add custom create logic here
    @user = User.new(user_params)
    @user.role = Role.where(name: Constants::CLIENT).first

    respond_to do |format|
      if @user.save
        format.html {redirect_to :back, notice: 'user was successfully created.'}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    super
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :role_id)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_cart
  def index
    @products = @cart.products.group_by(&:name)
  end

  def create
    products = @cart.products << Product.find(params[:product_id]) rescue []
    if products.present?
      flash[:success] = I18n.t('shopping_carts.create')
    else
      flash[:error] = I18n.t('shopping_carts.error')
    end
    redirect_to products_path
  end

  private
  def find_cart
    @cart = ShoppingCart.find_by(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def css_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-danger', notice: 'alert-success', warning: 'alert-warning', danger: 'alert-danger' }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper

  def total_price_product(product, quantity)
    (product.try(:[], :price) || 0 ).to_i * quantity
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%=link_to "Home", root_path %></li>
  <li role="presentation"><%=link_to "Carts", shopping_carts_path %></li>
  <% if user_signed_in? %>
      <li class='pull-right' role="presentation"><%=link_to "Logout", destroy_user_session_path %></li>
  <% else %>
      <li class='pull-right' role="presentation"><%=link_to "Login", new_user_session_path %></li>
      <li class='pull-right' role="presentation"><%=link_to "Sign Up", new_user_registration_path %></li>
<% end %>
</ul>
<div class="container" style="margin-top: 20px">
  <!-- Content here -->
  <% flash.each do |type, msg|%>
    <div class="alert <%= css_class_for(type) %> fade in alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      <%= msg.to_s.html_safe %>
    </div>
  <% end %>
  <%= yield %>

</div>

</body>
</html>

app/views/products/_listing.html.erb
  <table class="table table-striped table-wd">
    <thead>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Name</th>
        <th scope="row">Type</th>
        <th scope="row">Price</th>
        <th scope="row">Brand Name</th>
        <th scope="row">Add Item</th>
      </tr>
      <% products.each do |product|%>
        <tr>
          <td><%= product.name%></td>
          <td><%= product.item_type%></td>
          <td><%= product.price%></td>
          <td><%= product.try(:brand_name)%></td>
          <td><%= link_to "Add to cart", shopping_carts_path(product_id: product.id), method: :post %></td>
        </tr>
      <%end%>

    </tbody>
  </table>

app/views/products/_search.html.erb
<%= form_tag products_path, class: "form-horizontal", method: :get do %>
  <div class="input-group mb-3 col-md-8">
    <%= text_field_tag :search_term ,'', class: 'form-control' %>
    <%= submit_tag "Search", class: "btn btn-outline-secondary" %>
  </div>
<%end%>

app/views/products/index.html.erb
<% if current_user.present? && current_user.role.name == "Admin" %>
    <%= button_to "Add Product", new_product_path, method: :get, class: 'btn btn-outline-secondary pull-right' %>
<% end %>
<%= render 'search' %>

<br/>
<!-- Table -->
<% if @products.present? %>
    <%= render 'listing', products: @products %>
<% else %>
    <div class="panel panel-default">
      <div class="panel-body">No Products Found</div>
    </div>
<% end %>

app/views/products/new.html.erb
<%= form_for @product do |f|%>
  <div class="row">
    <div class="form-group col-md-6 ">
      <%= f.label :name, 'Product Name' %>
      <%=f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :item_type, 'Product Category' %>
      <%=f.text_field :item_type, class: 'form-control' %>
    </div>
  </div>

    <div class="row">
      <div class="form-group col-md-6">
        <%= f.label :brand_name, 'Brand Name' %>
        <%=f.text_field :brand_name, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <%= f.label :serial_number, 'Product Serial Number' %>
        <%=f.text_field :serial_number, class: 'form-control' %>
      </div>
    </div>


    <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :price, 'Price' %>
      <%=f.text_field :price, class: 'form-control' %>
    </div>
  </div>
  <%= submit_tag "Create", class: 'btn btn-primary'%>
<%end%>

app/views/shopping_carts/_listing.html.erb
<table class="table table-striped table-wd">
  <thead>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Name</th>
      <th scope="row">Type</th>
      <th scope="row">Price</th>
      <th scope="row">Quantity</th>
      <th scope="row">Total Price of Product</th>
    </tr>
    <% total = []%>
    <% products.each do |k, v|%>
     <% product = products[k].first %>
     <% quantity = products[k].count  %>
     <% total_item_price =total_price_product(product, quantity)%>
      <% total << total_item_price %>
      <tr>
        <td><%= product.name%></td>
        <td><%= product.item_type%></td>
        <td><%= product.price%></td>
        <td><%= quantity %></td>
        <td><%= total_item_price %></td>
      </tr>
    <%end%>

  </tbody>
    <tfoot>
    <tr>
      <td scope="row"></td>
      <td scope="row"></td>
      <td scope="row"></td>
      <td scope="row"></td>
      <td><%= total.sum %></td>
    </tr>
  </tfoot>
</table>

app/views/shopping_carts/index.html.erb
<% if @products.present?%>
  <%= render 'listing', products: @products %>
<% else %>
  <div class="panel panel-default">
    <div class="panel-body">No items Found</div>
  </div>
<% end %>